apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

namespace: healthpulse-dev

resources:
  - ../../base

images:
  - name: keneanyaragbu/healthpulse-backend
    newTag: 40-0369214

patches:
  - target:
      kind: Namespace
      name: healthpulse
    patch: |-
      - op: replace
        path: /metadata/name
        value: healthpulse-dev