apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -uat

namespace: healthpulse-uat

resources:
  - ../../base

images:
  - name: keneanyaragbu/healthpulse-backend
    newTag: latest

patches:
  - target:
      kind: Namespace
      name: healthpulse
    patch: |-
      - op: replace
        path: /metadata/name
        value: healthpulse-uat