apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: healthpulse-platform
    app.kubernetes.io/component: monitoring
    environment: dev
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.healthpulse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-grafana
                port:
                  number: 80
