apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthpulse-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/keneanyaragbu/healthpulse-platform.git
    targetRevision: feature/backend-devsecops-quality
    path: terraform/k3s/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: healthpulse-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true